# Generated by Django 4.2.6 on 2023-10-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='popularity',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
