# Generated by Django 4.2.6 on 2023-10-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_popularity_delete_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cover_image',
            new_name='image',
        ),
    ]
