# Generated by Django 4.2.6 on 2023-10-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_cover_image_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.TextField(default='No profile provided'),
        ),
    ]
