# Generated by Django 4.2.6 on 2023-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(default='Welcome to our Blog', max_length=122)),
                ('description', models.CharField(default='Welcome to our Blog', max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog/images'),
        ),
    ]
