# Generated by Django 4.2.6 on 2023-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpage_author_image_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(default='blog.jpg', upload_to='blog/images'),
        ),
    ]
