# Generated by Django 4.2.6 on 2023-10-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Liame Designs', max_length=122)),
                ('highlight', models.CharField(default='Precise concept design for stylish living', max_length=122)),
                ('description', models.TextField(default='If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.')),
                ('about_us_highlight', models.CharField(default='About Us', max_length=122)),
                ('about_us_description', models.TextField(default='If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='contact', max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(default='Nice Exhibition', max_length=122)),
                ('description', models.TextField(default='This is a nice exhibition')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='layer', max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Partner', max_length=122)),
                ('image', models.CharField(default='partner', max_length=122)),
                ('url', models.CharField(default='No url', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio')),
                ('name', models.CharField(max_length=122)),
                ('description', models.TextField(default='No description')),
                ('rating', models.IntegerField(default=0)),
                ('client', models.CharField(default='Private', max_length=50)),
                ('url', models.CharField(default='No url', max_length=100)),
                ('completed', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(default='Request for quote', max_length=122)),
                ('description', models.TextField(default='One of our services')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Service', max_length=122)),
                ('description', models.TextField(default='One of our services')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='testimonials')),
                ('testimony', models.TextField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
