# Generated by Django 4.2.6 on 2023-10-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_companyinfo_contact_exhibition_feature_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(default='icon', max_length=122),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='Feature', max_length=122),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='Portfolio', max_length=122),
        ),
    ]
