# Generated by Django 4.2.6 on 2023-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_feature_description_alter_feature_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quote_description',
            field=models.TextField(default='One of our services'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quote_highlight',
            field=models.CharField(default='Request for quote', max_length=122),
        ),
    ]
