# Generated by Django 4.2.6 on 2023-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_exhibition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(default='', upload_to='exhibitions'),
            preserve_default=False,
        ),
    ]
