# Generated by Django 4.2.6 on 2023-10-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_exhibition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
