# Generated by Django 4.2.6 on 2023-10-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_exhibition_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partners'),
        ),
    ]
