# Generated by Django 4.2.6 on 2023-10-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_companyinfo_support_email_companyinfo_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='No address', max_length=50),
        ),
    ]
