# Generated by Django 4.2.6 on 2023-10-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_companyinfo_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='google_map',
            field=models.TextField(default='No google map'),
        ),
    ]
