# Generated by Django 4.2.6 on 2023-10-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_companyinfo_google_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exhibition',
        ),
    ]
