# Generated by Django 4.2.6 on 2023-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_delete_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='introductory_video',
            field=models.CharField(default='Introductory Video', max_length=122),
        ),
    ]
