# Generated by Django 4.2.6 on 2023-10-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_companyinfo_introductory_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='description',
            new_name='home_page_description',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='highlight',
            new_name='home_page_highlight',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='blog_description',
            field=models.TextField(default='If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='blog_highlight',
            field=models.CharField(default='Blog', max_length=122),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='projects_description',
            field=models.TextField(default='If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='projects_highlight',
            field=models.CharField(default='Projects', max_length=122),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='services_description',
            field=models.TextField(default='If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='services_highlight',
            field=models.CharField(default='Services', max_length=122),
        ),
    ]
